[package]
name = "tmm"
version = "0.1.0"
edition = "2018"
authors = ["DomesticMoth"]
repository = "https://github.com/DomesticMoth/tmm"
readme = "README.md"
description = "Telegram bot"

[dependencies]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = 'abort'
strip = true

